server:
  port: 6763

spring:
  application:
    name: shop-cart-web
  #redis
  redis:
    host: 106.13.146.28
    port: 6379
    password: 123456
    jedis:
      pool:
        max-idle: 20

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/